name: CD

on:
  push:
    branches: [main]
  workflow_run:
    workflows: [CI]
    types:
      - completed

env:
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy-monorepo:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build affected apps
        run: pnpm turbo build --filter=...[main]

      - name: Deploy Website to Vercel
        uses: amondnet/vercel-action@v25
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEBSITE }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: ./apps/website
          alias-domains: |
            aloshy.ai
            www.aloshy.ai

      - name: Deploy Docs to Vercel
        uses: amondnet/vercel-action@v25
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DOCS }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: ./apps/docs
          alias-domains: |
            docs.aloshy.ai 