name: CD

on:
  push:
    branches: [main]
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  deploy-monorepo:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build affected apps
        run: pnpm turbo build --filter=...[main] 